version: '2'

services:
  rubybuild:
    volumes:
      - 'rubybin:/opt/devruby'
      - './ruby/dev_ruby/ruby:/home/workdir/ruby'
    build:
      context: ./docker_image/rubybuild
      dockerfile: "Dockerfile"
volumes:
  rubybin:
    driver: local
