version: '3'
services:
  search:
    image: elasticsearch:7.10.1
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  cache:
    image: memcached:1.4.24
    ports:
      - "11211:11211"
  rubygems:
    build:
      context: ./docker_image/rubygemsorg
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - APPBENCH_APPSERVER=$APPBENCH_APPSERVER
      - APPBENCH_DATABASE=$APPBENCH_DATABASE
      - APPBENCH_BENCHTOOL=$APPBENCH_BENCHTOOL
      - APPBENCH_REQPERSEC=$APPBENCH_REQPERSEC
      - APPBENCH_CPROF=$APPBENCH_CPROF
      - APPBENCH_RRROF=$APPBENCH_RRROF
      - SECRET_KEY_BASE=422813a913bb91e7b9bbce1cc499e0520bc1f43682ba305b54a307b3050ea4f6fa61dbd5c9f862ad0b5115b9efc47c636ea8b541956a175ab855558f6dba03fb
    depends_on:
      - search
      - cache
