version: '2'
services:
  discourse:
    build:
      context: ./docker_image/discourse
      dockerfile: "Dockerfile"
    volumes:
      - 'discourse_psql_data:/var/lib/postgresql'
    ports:
      - '3000:3000'
    environment:
      - APPBENCH_INSTALL_DIR="/var/www/discourse"
      - APPBENCH_APPSERVER=$APPBENCH_APPSERVER
      - APPBENCH_DATABASE=$APPBENCH_DATABASE
      - APPBENCH_BENCHTOOL=$APPBENCH_BENCHTOOL
      - APPBENCH_REQPERSEC=$APPBENCH_REQPERSEC
      - APPBENCH_CPROF=$APPBENCH_CPROF
      - APPBENCH_RRROF=$APPBENCH_RRROF
    stdin_open: true
    tty: true
volumes:
  discourse_psql_data:
    driver: local
    