version: '2'

services:
  redmine:
    volumes:
      - 'redmine_psql_data:/var/lib/postgresql'
    build:
      context: ./docker_image/redmine
      dockerfile: "Dockerfile"
    environment:
      - APPBENCH_INSTALL_DIR="/var/www/redmine"
      - APPBENCH_APPSERVER=$APPBENCH_APPSERVER
      - APPBENCH_DATABASE=$APPBENCH_DATABASE
      - APPBENCH_BENCHTOOL=$APPBENCH_BENCHTOOL
      - APPBENCH_REQPERSEC=$APPBENCH_REQPERSEC
      - APPBENCH_CPROF=$APPBENCH_CPROF
      - APPBENCH_RRROF=$APPBENCH_RRROF
      # - TZ=Asia/Kolkata
      # - DB_ADAPTER=postgresql
      # - DB_HOST=postgresql
      # - DB_PORT=5432
      # - DB_USER=redmine
      # - DB_PASS=password
      # - DB_NAME=redmine_production
      # - REDMINE_PORT=10083
      # - REDMINE_HTTPS=false
      # - REDMINE_RELATIVE_URL_ROOT=
      # - REDMINE_SECRET_TOKEN=
      # - REDMINE_SUDO_MODE_ENABLED=false
      # - REDMINE_SUDO_MODE_TIMEOUT=15
      # - REDMINE_CONCURRENT_UPLOADS=2
      # - REDMINE_BACKUP_SCHEDULE=
      # - REDMINE_BACKUP_EXPIRY=
      # - REDMINE_BACKUP_TIME=
      # - SMTP_ENABLED=false
      # - SMTP_METHOD=smtp
      # - SMTP_DOMAIN=www.example.com
      # - SMTP_HOST=smtp.gmail.com
      # - SMTP_PORT=587
      # - SMTP_USER=mailer@example.com
      # - SMTP_PASS=password
      # - SMTP_STARTTLS=true
      # - SMTP_AUTHENTICATION=:login
      # - IMAP_ENABLED=false
      # - IMAP_HOST=imap.gmail.com
      # - IMAP_PORT=993
      # - IMAP_USER=mailer@example.com
      # - IMAP_PASS=password
      # - IMAP_SSL=true
      # - IMAP_INTERVAL=30
    ports:
    - "3002:3000"
volumes:
  redmine_psql_data:
    driver: local