version: '2'
services:
  discourse:
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - 'postgresql_data:/var/lib/postgresql'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
volumes:
  postgresql_data:
    driver: local
    