#!/bin/bash

export APP_ROOT_DIR="/app/workdir"
export APP_VOLUME_DIR="/appbench"

# Logging configuration
export MODULE="${MODULE:-discourse}"
export APPBENCH_DEBUG="${APPBENCH_DEBUG:-true}"

# Paths
export DISCOURSE_BASE_DIR="${APP_ROOT_DIR}/discourse"
export DISCOURSE_CONF_FILE="${DISCOURSE_BASE_DIR}/config/discourse.conf"

# Discourse persistence configuration
export DISCOURSE_VOLUME_DIR="${APP_VOLUME_DIR}/discourse"
export DISCOURSE_DATA_TO_PERSIST="${DISCOURSE_DATA_TO_PERSIST:-plugins public/backups public/uploads}"

# System users (when running with a privileged user)
export DISCOURSE_DAEMON_USER="discourse"
export DISCOURSE_DAEMON_GROUP="discourse"

# Discourse configuration
export DISCOURSE_ENABLE_HTTPS="${DISCOURSE_ENABLE_HTTPS:-no}"
export DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER="${DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER:-80}"
export DISCOURSE_EXTERNAL_HTTPS_PORT_NUMBER="${DISCOURSE_EXTERNAL_HTTPS_PORT_NUMBER:-443}"
DISCOURSE_HOST="${DISCOURSE_HOST:-"${DISCOURSE_HOSTNAME:-}"}"
export DISCOURSE_HOST="${DISCOURSE_HOST:-locahost}"
export DISCOURSE_PORT_NUMBER="${DISCOURSE_PORT_NUMBER:-3000}"
DISCOURSE_SKIP_BOOTSTRAP="${DISCOURSE_SKIP_BOOTSTRAP:-"${DISCOURSE_SKIP_INSTALL:-}"}"
export DISCOURSE_SKIP_BOOTSTRAP="${DISCOURSE_SKIP_BOOTSTRAP:-}" # only used during the first initialization
export DISCOURSE_SITE_NAME="${DISCOURSE_SITE_NAME:-My site!}" # only used during the first initialization
export DISCOURSE_ENV="${DISCOURSE_ENV:-production}"
export DISCOURSE_PRECOMPILE_ASSETS="${DISCOURSE_PRECOMPILE_ASSETS:-yes}"
export DISCOURSE_ENABLE_CONF_PERSISTENCE="${DISCOURSE_ENABLE_CONF_PERSISTENCE:-no}"
export DISCOURSE_EXTRA_CONF_CONTENT="${DISCOURSE_EXTRA_CONF_CONTENT:-yes}"
export DISCOURSE_PASSENGER_SPAWN_METHOD="${DISCOURSE_PASSENGER_SPAWN_METHOD:-direct}"
export DISCOURSE_PASSENGER_EXTRA_FLAGS="${DISCOURSE_PASSENGER_EXTRA_FLAGS:-}"


# Discourse credentials
export DISCOURSE_USERNAME="${DISCOURSE_USERNAME:-user}" # only used during the first initialization
export DISCOURSE_PASSWORD="${DISCOURSE_PASSWORD:-appbench123}" # only used during the first initialization
export DISCOURSE_EMAIL="${DISCOURSE_EMAIL:-appbench@example.com}" # only used during the first initialization
export DISCOURSE_FIRST_NAME="${DISCOURSE_FIRST_NAME:-BenchFirstName}" # only used during the first initialization
export DISCOURSE_LAST_NAME="${DISCOURSE_LAST_NAME:-BenchLastName}" # only used during the first initialization

# Discourse SMTP credentials
DISCOURSE_SMTP_HOST="${DISCOURSE_SMTP_HOST:-"${SMTP_HOST:-}"}"
export DISCOURSE_SMTP_HOST="${DISCOURSE_SMTP_HOST:-}"
DISCOURSE_SMTP_PORT_NUMBER="${DISCOURSE_SMTP_PORT_NUMBER:-"${SMTP_PORT:-}"}"
DISCOURSE_SMTP_PORT_NUMBER="${DISCOURSE_SMTP_PORT_NUMBER:-"${DISCOURSE_SMTP_PORT:-}"}"
export DISCOURSE_SMTP_PORT_NUMBER="${DISCOURSE_SMTP_PORT_NUMBER:-}"
DISCOURSE_SMTP_USER="${DISCOURSE_SMTP_USER:-"${SMTP_USER:-}"}"
export DISCOURSE_SMTP_USER="${DISCOURSE_SMTP_USER:-}"
DISCOURSE_SMTP_PASSWORD="${DISCOURSE_SMTP_PASSWORD:-"${SMTP_PASSWORD:-}"}"
export DISCOURSE_SMTP_PASSWORD="${DISCOURSE_SMTP_PASSWORD:-}"
DISCOURSE_SMTP_PROTOCOL="${DISCOURSE_SMTP_PROTOCOL:-"${SMTP_PROTOCOL:-}"}"
export DISCOURSE_SMTP_PROTOCOL="${DISCOURSE_SMTP_PROTOCOL:-}"
DISCOURSE_SMTP_AUTH="${DISCOURSE_SMTP_AUTH:-"${SMTP_AUTH:-}"}"
export DISCOURSE_SMTP_AUTH="${DISCOURSE_SMTP_AUTH:-login}"

# Database configuration
export POSTGRESQL_HOST="postgresql"
export POSTGRESQL_PORT_NUMBER="5432"
export POSTGRESQL_ROOT_PASSWORD=""
export POSTGRESQL_ROOT_USER="postgres"

# Database configuration
export DISCOURSE_DEFAULT_DATABASE_HOST="postgresql"
export DISCOURSE_DATABASE_NAME="appbench_discourse"

export DISCOURSE_DATABASE_HOST="${POSTGRESQL_HOST}"
export DISCOURSE_DATABASE_PORT_NUMBER="${POSTGRESQL_PORT_NUMBER}"
export DISCOURSE_DATABASE_NAME="${DISCOURSE_DATABASE_NAME}"
export DISCOURSE_DATABASE_USER="${DISCOURSE_DATABASE_USER:-appbench_user}"
export DISCOURSE_DATABASE_PASSWORD="${DISCOURSE_DATABASE_PASSWORD:-}"


# Redis configuration
export DISCOURSE_DEFAULT_REDIS_HOST="redis" # only used at build time
DISCOURSE_REDIS_HOST="${DISCOURSE_REDIS_HOST:-"${REDIS_HOST:-}"}"
export DISCOURSE_REDIS_HOST="${DISCOURSE_REDIS_HOST:-$DISCOURSE_DEFAULT_REDIS_HOST}"
DISCOURSE_REDIS_PORT_NUMBER="${DISCOURSE_REDIS_PORT_NUMBER:-"${REDIS_PORT_NUMBER:-}"}"
export DISCOURSE_REDIS_PORT_NUMBER="${DISCOURSE_REDIS_PORT_NUMBER:-6379}"
DISCOURSE_REDIS_PASSWORD="${DISCOURSE_REDIS_PASSWORD:-"${REDIS_PASSWORD:-}"}"
export DISCOURSE_REDIS_PASSWORD="${DISCOURSE_REDIS_PASSWORD:-}"
