#!/bin/sh

# start PostgreSQL
/etc/init.d/postgresql start
sleep 5

gem update --system
gem install facter
gem install stackprof

bundle install --jobs 3 --retry 5 --path ./vendor/bundle

# create dartabase
RAILS_ENV=production bundle exec rails db:create db:migrate

# TEMP
chown -R redmine result/ tmp/
